wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.17.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720804974
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      3:
      - 3
      - 8
      - 19
      - 23
      4: 3.10.11
      5: 0.17.4
      8:
      - 1
      - 3
      - 5
      10:
      - 9
      13: windows-amd64
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 10
max_iter:
  desc: null
  value: 2000
